project:
  name: Ozon Code Platform Purchase API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9101
  path: /metrics

jaeger:
  service: "cnm-purchase-api"
  host: "jaeger"
  port: ":6831"
  #host: "0.0.0.0"
  #port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  #host: postgres
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: cnm_purchase_api
  sslmode: disable
  migrations: migrations
  driver: pgx

kafka:
  capacity: 512
  topic: "cnm-purchase-events"
  groupId: "cnm-purchase-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
