// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cnm_purchase_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CnmPurchaseApiServiceClient is the client API for CnmPurchaseApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CnmPurchaseApiServiceClient interface {
	DescribePurchaseV1(ctx context.Context, in *DescribePurchaseV1Request, opts ...grpc.CallOption) (*DescribePurchaseV1Response, error)
	CreatePurchaseV1(ctx context.Context, in *CreatePurchaseV1Request, opts ...grpc.CallOption) (*CreatePurchaseV1Response, error)
	ListPurchasesV1(ctx context.Context, in *ListPurchasesV1Request, opts ...grpc.CallOption) (*ListPurchasesV1Response, error)
	RemovePurchaseV1(ctx context.Context, in *RemovePurchaseV1Request, opts ...grpc.CallOption) (*RemovePurchaseV1Response, error)
}

type cnmPurchaseApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCnmPurchaseApiServiceClient(cc grpc.ClientConnInterface) CnmPurchaseApiServiceClient {
	return &cnmPurchaseApiServiceClient{cc}
}

func (c *cnmPurchaseApiServiceClient) DescribePurchaseV1(ctx context.Context, in *DescribePurchaseV1Request, opts ...grpc.CallOption) (*DescribePurchaseV1Response, error) {
	out := new(DescribePurchaseV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/DescribePurchaseV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cnmPurchaseApiServiceClient) CreatePurchaseV1(ctx context.Context, in *CreatePurchaseV1Request, opts ...grpc.CallOption) (*CreatePurchaseV1Response, error) {
	out := new(CreatePurchaseV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/CreatePurchaseV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cnmPurchaseApiServiceClient) ListPurchasesV1(ctx context.Context, in *ListPurchasesV1Request, opts ...grpc.CallOption) (*ListPurchasesV1Response, error) {
	out := new(ListPurchasesV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/ListPurchasesV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cnmPurchaseApiServiceClient) RemovePurchaseV1(ctx context.Context, in *RemovePurchaseV1Request, opts ...grpc.CallOption) (*RemovePurchaseV1Response, error) {
	out := new(RemovePurchaseV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/RemovePurchaseV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CnmPurchaseApiServiceServer is the server API for CnmPurchaseApiService service.
// All implementations must embed UnimplementedCnmPurchaseApiServiceServer
// for forward compatibility
type CnmPurchaseApiServiceServer interface {
	DescribePurchaseV1(context.Context, *DescribePurchaseV1Request) (*DescribePurchaseV1Response, error)
	CreatePurchaseV1(context.Context, *CreatePurchaseV1Request) (*CreatePurchaseV1Response, error)
	ListPurchasesV1(context.Context, *ListPurchasesV1Request) (*ListPurchasesV1Response, error)
	RemovePurchaseV1(context.Context, *RemovePurchaseV1Request) (*RemovePurchaseV1Response, error)
	mustEmbedUnimplementedCnmPurchaseApiServiceServer()
}

// UnimplementedCnmPurchaseApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCnmPurchaseApiServiceServer struct {
}

func (UnimplementedCnmPurchaseApiServiceServer) DescribePurchaseV1(context.Context, *DescribePurchaseV1Request) (*DescribePurchaseV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribePurchaseV1 not implemented")
}
func (UnimplementedCnmPurchaseApiServiceServer) CreatePurchaseV1(context.Context, *CreatePurchaseV1Request) (*CreatePurchaseV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePurchaseV1 not implemented")
}
func (UnimplementedCnmPurchaseApiServiceServer) ListPurchasesV1(context.Context, *ListPurchasesV1Request) (*ListPurchasesV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPurchasesV1 not implemented")
}
func (UnimplementedCnmPurchaseApiServiceServer) RemovePurchaseV1(context.Context, *RemovePurchaseV1Request) (*RemovePurchaseV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePurchaseV1 not implemented")
}
func (UnimplementedCnmPurchaseApiServiceServer) mustEmbedUnimplementedCnmPurchaseApiServiceServer() {}

// UnsafeCnmPurchaseApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CnmPurchaseApiServiceServer will
// result in compilation errors.
type UnsafeCnmPurchaseApiServiceServer interface {
	mustEmbedUnimplementedCnmPurchaseApiServiceServer()
}

func RegisterCnmPurchaseApiServiceServer(s grpc.ServiceRegistrar, srv CnmPurchaseApiServiceServer) {
	s.RegisterService(&CnmPurchaseApiService_ServiceDesc, srv)
}

func _CnmPurchaseApiService_DescribePurchaseV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePurchaseV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CnmPurchaseApiServiceServer).DescribePurchaseV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/DescribePurchaseV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CnmPurchaseApiServiceServer).DescribePurchaseV1(ctx, req.(*DescribePurchaseV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CnmPurchaseApiService_CreatePurchaseV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CnmPurchaseApiServiceServer).CreatePurchaseV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/CreatePurchaseV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CnmPurchaseApiServiceServer).CreatePurchaseV1(ctx, req.(*CreatePurchaseV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CnmPurchaseApiService_ListPurchasesV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchasesV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CnmPurchaseApiServiceServer).ListPurchasesV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/ListPurchasesV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CnmPurchaseApiServiceServer).ListPurchasesV1(ctx, req.(*ListPurchasesV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CnmPurchaseApiService_RemovePurchaseV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePurchaseV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CnmPurchaseApiServiceServer).RemovePurchaseV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/RemovePurchaseV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CnmPurchaseApiServiceServer).RemovePurchaseV1(ctx, req.(*RemovePurchaseV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CnmPurchaseApiService_ServiceDesc is the grpc.ServiceDesc for CnmPurchaseApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CnmPurchaseApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService",
	HandlerType: (*CnmPurchaseApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribePurchaseV1",
			Handler:    _CnmPurchaseApiService_DescribePurchaseV1_Handler,
		},
		{
			MethodName: "CreatePurchaseV1",
			Handler:    _CnmPurchaseApiService_CreatePurchaseV1_Handler,
		},
		{
			MethodName: "ListPurchasesV1",
			Handler:    _CnmPurchaseApiService_ListPurchasesV1_Handler,
		},
		{
			MethodName: "RemovePurchaseV1",
			Handler:    _CnmPurchaseApiService_RemovePurchaseV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/cnm_purchase_api/v1/cnm_purchase_api.proto",
}
