// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: ozonmp/cnm_purchase_api/v1/cnm_purchase_api.proto

/*
Package cnm_purchase_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package cnm_purchase_api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_CnmPurchaseApiService_DescribePurchaseV1_0(ctx context.Context, marshaler runtime.Marshaler, client CnmPurchaseApiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribePurchaseV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["purchase_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "purchase_id")
	}

	protoReq.PurchaseId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "purchase_id", err)
	}

	msg, err := client.DescribePurchaseV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_CnmPurchaseApiService_DescribePurchaseV1_0(ctx context.Context, marshaler runtime.Marshaler, server CnmPurchaseApiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribePurchaseV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["purchase_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "purchase_id")
	}

	protoReq.PurchaseId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "purchase_id", err)
	}

	msg, err := server.DescribePurchaseV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterCnmPurchaseApiServiceHandlerServer registers the http handlers for service CnmPurchaseApiService to "mux".
// UnaryRPC     :call CnmPurchaseApiServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCnmPurchaseApiServiceHandlerFromEndpoint instead.
func RegisterCnmPurchaseApiServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CnmPurchaseApiServiceServer) error {

	mux.Handle("GET", pattern_CnmPurchaseApiService_DescribePurchaseV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/DescribePurchaseV1", runtime.WithHTTPPathPattern("/v1/purchases/{purchase_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CnmPurchaseApiService_DescribePurchaseV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CnmPurchaseApiService_DescribePurchaseV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterCnmPurchaseApiServiceHandlerFromEndpoint is same as RegisterCnmPurchaseApiServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCnmPurchaseApiServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterCnmPurchaseApiServiceHandler(ctx, mux, conn)
}

// RegisterCnmPurchaseApiServiceHandler registers the http handlers for service CnmPurchaseApiService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCnmPurchaseApiServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCnmPurchaseApiServiceHandlerClient(ctx, mux, NewCnmPurchaseApiServiceClient(conn))
}

// RegisterCnmPurchaseApiServiceHandlerClient registers the http handlers for service CnmPurchaseApiService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CnmPurchaseApiServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CnmPurchaseApiServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CnmPurchaseApiServiceClient" to call the correct interceptors.
func RegisterCnmPurchaseApiServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CnmPurchaseApiServiceClient) error {

	mux.Handle("GET", pattern_CnmPurchaseApiService_DescribePurchaseV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/ozonmp.cnm_purchase_api.v1.CnmPurchaseApiService/DescribePurchaseV1", runtime.WithHTTPPathPattern("/v1/purchases/{purchase_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CnmPurchaseApiService_DescribePurchaseV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CnmPurchaseApiService_DescribePurchaseV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_CnmPurchaseApiService_DescribePurchaseV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "purchases", "purchase_id"}, ""))
)

var (
	forward_CnmPurchaseApiService_DescribePurchaseV1_0 = runtime.ForwardResponseMessage
)
